resources:
- repo: self

# Trigger builds on commits to branches
trigger:
  branches:
    exclude:
    - '*'
  tags:
    include:
    - '*'

# Do not trigger builds on PRs
pr: none

extends:
  template: azure-pipelines-release-template.yml
  parameters:
    dockerRegistryServiceConnection: '6e355485-28e3-480f-a9c7-e5f07af9d127'
    imageRepository: 'skillsrecommenderapi'
    dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
    vmImageName: 'ubuntu-latest'
    tags: '$(Build.SourceBranchName)'