version: '3.4'

services:
  skillingplanapi.application:
    image: ${DOCKER_REGISTRY-}skillingplanapiapplication
    build:
      context: .
      dockerfile: src/SkillingPlanApi.Application/Dockerfile.dev
    environment:
        - CORS__AllowedOrigins=http://localhost,http://localhost:3000

    ports:
      - 5000:5000

